# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaeman's blog
email: ajmbell@bawi.org
description: > # this means to ignore newlines until "baseurl:"
  Jaeman An's blog. Software engineering, Software development, Android,
  Golang, Computer Science, Algorithm, Graphics, etc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kuss.pe.kr" # the base hostname & protocol for your site
twitter_username: ajmbell
github_username:  kuss 

# Build settings
markdown: redcarpet 
redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "superscript", "highlight", "footnotes"]
